### ISSUE TITLE
[Feature request] Content editing

### ISSUE THREAD

**Issue by mdorda** [NodeBB/nodebb-plugin-gdpr#13]
Thank you so much for the extension! I have no idea how much work it would take, but it would be great to edit the content of these texts:

1. https://community.windy.com/me/consent
2. The text during registration/login:
![image](https://user-images.githubusercontent.com/6674990/80601275-e4805b00-8a2d-11ea-91a1-3f9573a8c16d.png)

Or is there any way how to edit that without changing the plugin?

**Comment by julianlam** [comment]
This plugin only exposes new ACP pages and enforces GDPR consent if needed. The actual consent dialog is in NodeBB core, and you can customize the content with `nodebb-plugin-customize` :smile:
