### ISSUE TITLE
Can't login after activating plugin.

### ISSUE THREAD

**Issue by paviro** [NodeBB/nodebb-plugin-gdpr#3]
It seems like it is impossible to actually login after enabling the module :/ 
I instantly get an alert saying I haven't consented even when I am not logged in and I can't since the alert pops up again when you dismiss it.

![sdsdsd](https://user-images.githubusercontent.com/992826/40203615-10da8674-5a26-11e8-83c1-85c3a6e7f70b.png)

**Comment by julianlam** [comment]
Thanks for reporting, will look into it tonight

**Comment by paviro** [comment]
Let me know if you need any more infos! I am on 1.9.2 and tried a few rebuilds before and after enabling the force consent option.

**Comment by jadelaop** [comment]
Same problem. 1.9.2 too.

The problem is only when user is disconnected and checkbox 'Require Consent for Existing Users' active.

With connected users: No problem.
With disabled checkbox in admin: No problem.

I think that a simple solution can be disable alert in Login page.

**Comment by julianlam** [comment]
v1.0.2

**Comment by julianlam** [comment]
Actually, issue was guests should not see that modal at all :smile: they do not require consent to read anonymously.

**Comment by paviro** [comment]
Neat! Any update on the wrong consent state in the admin panel? I and also new users are still shown as not having consented even tough they wouldn’t have been able to register if they hadn’t. And I definitely also consented.

**Comment by julianlam** [comment]
Hi @paviro, I'm not aware of any issues with incorrect consent state being reported in the admin panel, do you have reproduction steps?

**Comment by paviro** [comment]
Well not really. Activating the plugin and the reported states are incorrect. I consented before installing the plugin but it still shows the red X for my account. Not sure with which infos I can provide you.

**Comment by julianlam** [comment]
What does it show in the "Your Rights & Consent" page? That you're consented?

**Comment by paviro** [comment]
Yes exactly.

**Comment by paviro** [comment]
![sdsd1](https://user-images.githubusercontent.com/992826/40245311-9665daba-5ac5-11e8-946d-139c8671c3b3.png)
![sdsd2](https://user-images.githubusercontent.com/992826/40245315-97eff0e6-5ac5-11e8-8d2a-a9cdda721824.png)
