### ISSUE TITLE
User can’t get past consent alert

### ISSUE THREAD

**Issue by paviro** [NodeBB/nodebb-plugin-gdpr#7]
I just got a message from one of my users. Any idea how I can find the problem?
![bb45b698-d4d3-4683-bc30-54361c90fda6](https://user-images.githubusercontent.com/992826/40563436-0c3d8680-6065-11e8-9170-46bddb775908.png)

**Comment by julianlam** [comment]
Latest version of plugin?

**Comment by paviro** [comment]
Yes :)

**Comment by paviro** [comment]
Any news on this? 
![img_3636](https://user-images.githubusercontent.com/992826/41369851-59868af0-6f46-11e8-9142-460c3de22c69.png)
https://github.com/MichMich/MagicMirror/issues/1295

**Comment by julianlam** [comment]
Unfortunately I am not able to reproduce -- what version of NodeBB are you on, and what commit hash?

`git rev-parse HEAD`

I have a feeling this has been fixed already

**Comment by julianlam** [comment]
Nevermind, I have successfully reproduced :cry:

**Comment by julianlam** [comment]
v1.0.5

**Comment by paviro** [comment]
Thank you!
